### PR TITLE
Fixed #50.

### LINKED ISSUE #50: Aporia crashes in "Replace All" when Find==Replace
I want to fix case inconsistency a nimrod file (N.nim on ParticleBench, btw). So, I'm using the 'Style Insensitive' search, and I want to run a replace all with the same name string in Find and Replace (for example, "PrintFrames"). Aporia consistently crashes when I try to do that. If I find for some string (ex: "PrintFrames") but ask it to replace to another different string (ex: "asdf") replace all works. Manually clicking on next and then replace for each ocurrence works.

Below the console output when I run aporia and trigger the bug:

```
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `GtkRange::activate-slider' of type `gboolean' from rc file value "((GString*) 0x91acab0)" of type `GString'

(aporia:3223): GLib-ERROR **: /build/buildd/glib2.0-2.38.1/./glib/gmem.c:175: failed to allocate 8192 bytes
Trace/breakpoint trap (core dumped)
```

### PR DESCRIPTION
**Pull request by achesak**

### CODE REVIEW

File: search.nim [hunk 1]
```diff
@@ -380,6 +380,18 @@ proc replaceAll*(win: var utils.MainWin, find, replace: cstring): int =
...
+
+  # Check how many occurrences there are of the search string.
+  var startIter: TTextIter
+  buffer.getStartIter(addr(startIter))
+  var endIter: TTextIter
+  buffer.getEndIter(addr(endIter))
+  var text = $buffer.getText(addr(startIter), addr(endIter), false)
+  var maxCount : int
+  if win.autoSettings.search == SearchCaseInsens or win.autoSettings.search == SearchStyleInsens:
+    maxCount = count(unicode.toLower(text), unicode.toLower($find))
```
Comment (dom96) [inline search.nim]: Is there no better way to solve this bug? This seems like it has the potential for slowing this procedure down considerably.

**Comment by achesak** [comment]
Changed the fix to check the starting 'found' position instead.

File: search.nim [hunk 2]
```diff
@@ -403,6 +404,9 @@ proc replaceAll*(win: var utils.MainWin, find, replace: cstring): int =
       found = ret[2]
   
     if found:
+      if addr(startMatch).getOffset() <= lastPos:
+        break
+      lastPos = addr(startMatch).getOffset()
```
Comment (dom96) [inline search.nim]: Hrm. I'm wondering if this will break the following scenario:

```nim
var x = 5
var y = 4
# Cursor is here.
var x = 5
var x = 5
```

I replace all ``x`` with ``blah``. Will all x's still be replaced? or just the two below the cursor?

Comment (achesak) [inline search.nim]: They're all replaced, I don't believe any of 'Replace All' depends on cursor position.

Comment (dom96) [inline search.nim]: Good :)
